// Application Configuration & Constants

export const APP_CONFIG = {
  name: 'NEXA',
  fullName: 'NEXA - Pre-Order & Business Operations Suite',
  version: '3.0.0',
  description: 'Sistem Operasional Pre-Order & Manajemen Bisnis Modern',
  storageKeys: {
    PRODUCTS: 'po_universal_products',
    ORDERS: 'po_universal_orders',
    EXPENSES: 'po_universal_expenses',
    SETTINGS: 'po_universal_settings',
    DRAFT_ORDER: 'po_universal_draft_order',
    OFFLINE_QUEUE: 'po_universal_offline_queue',
    IS_SAMPLE_DATA: 'po_universal_is_sample_data',
  },
  defaultSettings: {
    businessName: 'NEXA Artisan Kitchen',
    businessTagline: 'Katering Premium & Aneka Kuliner Pre-Order',
    phone: '6281234567890',
    address: 'Jl. Senopati No. 28, Kebayoran Baru, Jakarta Selatan',
    bankName: 'BCA',
    accountName: 'NEXA Artisan Kitchen',
    accountNumber: '8830192841',
    qrisNote: 'Tersedia QRIS statis di kasir atau scan saat pengiriman',
    googleAppsScriptUrl: '',
    currency: 'IDR',
    dateFormat: 'DD/MM/YYYY',
    autoSync: true,
  },
  expenseCategories: [
    'Bahan Baku',
    'Packaging',
    'Transportasi & Kurir',
    'Pemasaran & Iklan',
    'Gaji & Upah',
    'Operasional & Utilitas',
    'Peralatan',
    'Lainnya',
  ],
  productUnits: [
    'pcs',
    'porsi',
    'box',
    'paket',
    'kg',
    'gram',
    'liter',
    'botol',
    'cup',
    'lusin',
  ],
  paymentMethods: [
    'Cash / Tunai',
    'Transfer Bank',
    'QRIS',
    'E-Wallet (GoPay/OVO/Dana)',
    'Lainnya',
  ],
  orderStatuses: [
    { key: 'new', label: 'Baru', desc: 'Pesanan baru masuk & tercatat' },
    { key: 'processing', label: 'Diproses', desc: 'Sedang disiapkan / dimasak' },
    { key: 'ready', label: 'Siap', desc: 'Selesai disiapkan, siap kirim / pickup' },
    { key: 'completed', label: 'Selesai', desc: 'Pesanan telah diterima pelanggan' },
    { key: 'cancelled', label: 'Dibatalkan', desc: 'Pesanan dibatalkan' },
  ],
  paymentStatuses: [
    { key: 'unpaid', label: 'Belum Lunas' },
    { key: 'dp', label: 'DP' },
    { key: 'paid', label: 'Lunas' },
  ],
};
